extends:
  - eslint:recommended
  - llama
  - prettier

env:
  shared-node-browser: true
  node: true
  jest: true
  commonjs: true

parser: babel-eslint
parserOptions:
  sourceType: module

globals:
  # Support starts at IE10
  ArrayBuffer: true
  Uint8ClampedArray: true
  Int8Array: true
  Uint8Array: true
  Int16Array: true
  Uint16Array: true
  Int32Array: true
  Uint32Array: true
  Float32Array: true
  Float64Array: true
